// Generates assets/css/tokens.css: Material 3 (2025 / Expressive spec) colour
// roles, one dark scheme per area of the site. Run after changing a seed:
//   npm run build:tokens
// (tsx is needed because the colour library ships extensionless ESM imports.)
import { writeFileSync } from "node:fs";
import { DynamicScheme, Hct, MaterialDynamicColors, SchemeContent, TonalPalette, hexFromArgb } from "@material/material-color-utilities";

/**
 * Each area keeps its identity colour as the seed. "Content" keeps the seed's
 * own chroma (the brand violet stays the brand violet) and derives calm,
 * slightly tinted surfaces. `tertiary` pins the accent pair a page has always
 * used (Voidline's cyan, the Grimoire's teal) instead of the computed one.
 */
const AREAS = [
  { selector: ":root", name: "Okami (home, 404)", seed: "#a568ff" },
  { selector: ".voidline-page", name: "Voidline", seed: "#9748f4", tertiary: "#6ee7f2" },
  { selector: ".luna-page, .luna-legal-page", name: "LunaEcho", seed: "#ff85d2", tertiary: "#8bc7ff" },
  { selector: ".mirrorgate-page", name: "The Mirrored Realms (grimoire)", seed: "#c9a55a", tertiary: "#79c9bf" },
];

const argb = (hex) => parseInt(hex.slice(1), 16) | 0xff000000;
const roles = new MaterialDynamicColors().allColors.filter((role) => role && typeof role.getArgb === "function");
const kebab = (name) => name.replace(/_/g, "-").toLowerCase();

function scheme({ seed, tertiary }) {
  const source = Hct.fromInt(argb(seed));
  const base = new SchemeContent(source, true, 0, "2025", "phone");
  if (!tertiary) return base;
  return new DynamicScheme({
    sourceColorHct: source, variant: base.variant, contrastLevel: 0, isDark: true, specVersion: "2025", platform: "phone",
    primaryPalette: base.primaryPalette, secondaryPalette: base.secondaryPalette,
    tertiaryPalette: TonalPalette.fromInt(argb(tertiary)),
    neutralPalette: base.neutralPalette, neutralVariantPalette: base.neutralVariantPalette,
  });
}

const blocks = AREAS.map((area) => {
  const s = scheme(area);
  const lines = roles.map((role) => `  --md-sys-color-${kebab(role.name)}: ${hexFromArgb(role.getArgb(s))};`);
  return `/* ${area.name} – seed ${area.seed}${area.tertiary ? `, tertiary ${area.tertiary}` : ""} */\n${area.selector} {\n${lines.join("\n")}\n}`;
});

writeFileSync(
  new URL("../assets/css/tokens.css", import.meta.url),
  `/* Generated by tools/build-tokens.mjs (M3 2025 spec, dark). Do not edit by hand. */\n${blocks.join("\n\n")}\n`,
);
console.log(`tokens.css written: ${roles.length} roles × ${AREAS.length} areas.`);
