// Generates assets/css/shapes.css: the Material 3 Expressive shape library as
// CSS custom properties (clip-path polygons in %, so they scale with any box).
// Every shape has the same number of points, which lets CSS morph one shape
// into another with a plain transition or keyframes – the M3 "shape morph".
//   npm run build:shapes
import { writeFileSync } from "node:fs";

const POINTS = 72;

const radius = {
  circle: () => 1,
  // Scalloped circles ("cookie" shapes).
  cookie4: (t) => 1 - 0.16 * (1 - Math.cos(4 * t)) / 2,
  cookie6: (t) => 1 - 0.11 * (1 - Math.cos(6 * t)) / 2,
  cookie9: (t) => 1 - 0.09 * (1 - Math.cos(9 * t)) / 2,
  cookie12: (t) => 1 - 0.07 * (1 - Math.cos(12 * t)) / 2,
  // Four soft petals.
  clover: (t) => 0.7 + 0.3 * Math.abs(Math.cos(2 * t)) ** 0.6,
  // Many small rays.
  sunny: (t) => 1 - 0.07 * (1 - Math.cos(8 * t)) / 2,
  burst: (t) => 1 - 0.2 * (1 - Math.cos(12 * t)) / 2,
  // Soft rounded triangle and pentagon ("gem").
  triangle: (t) => 0.8 + 0.2 * Math.cos(3 * (t + Math.PI / 2)) ** 3,
  gem: (t) => 0.88 + 0.12 * Math.cos(5 * (t + Math.PI / 2)),
};

function polygon(r) {
  const points = [];
  for (let index = 0; index < POINTS; index += 1) {
    const t = (index / POINTS) * Math.PI * 2 - Math.PI / 2;
    const length = 50 * r(t);
    points.push(`${(50 + length * Math.cos(t)).toFixed(2)}% ${(50 + length * Math.sin(t)).toFixed(2)}%`);
  }
  return `polygon(${points.join(",")})`;
}

const properties = Object.entries(radius).map(([name, r]) => `  --shape-${name}: ${polygon(r)};`).join("\n");
const loop = ["cookie12", "clover", "sunny", "cookie6", "gem", "cookie12"];
const frames = loop.map((name, index) => `  ${Math.round((index / (loop.length - 1)) * 100)}% { clip-path: var(--shape-${name}); }`).join("\n");

writeFileSync(
  new URL("../assets/css/shapes.css", import.meta.url),
  `/* Generated by tools/build-shapes.mjs. Do not edit by hand. */
:root {
${properties}
}

/* Slow ambient morph through the library (hero shapes, loading states). */
@keyframes shape-morph {
${frames}
}
`,
);
console.log(`shapes.css written: ${Object.keys(radius).length} shapes × ${POINTS} points.`);
